---
# Install php packages

- name: unwanted packages are removed
  package:
    name: "{{ php_packages_remove }}"
    state: absent
  become: true
  when: php_remove_packages

- name: prereq repositories are installed
  package:
    name: "{{ php_packages_repos }}"
    state: "{{ php_packages_state }}"
  become: true

- name: prereq packages are installed
  package:
    name: "{{ php_packages_prereq }}"
    state: "{{ php_packages_state }}"
  become: true

- name: packages are installed
  package:
    name: "{{ php_packages_install }}"
    state: "{{ php_packages_state }}"
  become: true
