---
# Template configuration files for php

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ php_templates_copy }}"
  when: php_copy_templates
